# This is the First Workflow for Testing with Github Actions

name: Release Version
on:
  workflow_dispatch:
    inputs:
     new_version:
       description: "The version to release"
       required: true
env:
  ENCODING: LC_CTYPE=en_US.UTF-8
  DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
jobs:
  release-version:
    runs-on: macos-10.15
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Create Version
        run: | 
            agvtool new-marketing-version "${{ github.event.inputs.new_version }}"
            sed -i '' -e 's/\(s\.version.*=\).*/\1 "${{ github.event.inputs.new_version }}"/' ./Swinject.podspec
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -a -m "Update the version to ${{ github.event.inputs.new_version }}"
            git tag "${{ github.event.inputs.new_version }}"
            git push --atomic
        shell: bash
      - name: Github Release Draft
        run: | 
            gh release create v"${{ github.event.inputs.new_version }}" --draft
        shell: bash
      - name: Publish PodSpec
        run: | 
            export "${{ env. ENCODING }}" | pod lib lint
        shell: bash