# This is the First Workflow for Testing with Github Actions

name: Testing
on:
  workflow_dispatch:
env: 
  PROJECT: Swinject.xcodeproj
jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
       include:
         - platform-version: iOS
           JOB: "XCODE"
           DEST: "OS=14.4,name=iPhone 8"
           SCHEME: "Swinject-iOS"
           SDK: "iphonesimulator"
           ACTION: "test"
           PLATFORM: "iOS"
         - platform-version: macOS
           JOB: "XCODE"
           DEST: "arch=x86_64"
           SCHEME: "Swinject-macOS"
           SDK: "macosx"
           ACTION: "test"
           PLATFORM: "OSX"
         - platform-version: tvOS
           JOB: "XCODE"
           DEST: "OS=14.3,name=Apple TV 4K"
           SCHEME: "Swinject-tvOS"
           SDK: "appletvsimulator"
           ACTION: "test"
           PLATFORM: "tvOS"
         - platform-version: watchOS
           JOB: "XCODE"
           DEST: "OS=7.2,name=Apple Watch Series 6 - 44mm"
           SCHEME: "Swinject-watchOS"
           SDK: "watchsimulator"
           ACTION: "build"
           PLATFORM: "watchOS"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Testing Framework for - "${{ matrix.PLATFORM }}"
        run: xcodebuild "${{ matrix.ACTION }}" -project "${{ env.PROJECT }}" -scheme "${{ matrix.SCHEME }}" -sdk "${{ matrix.SDK }}" -destination "${{ matrix.DEST }}" -configuration Release ENABLE_TESTABILITY=YES | xcpretty
        shell: bash